
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Library {
	public static void main(String arg[]) {
		lab3.ex2.UIApplication.run(arg);
		//comment for commit 2
	}
}
